apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Collects metrics and aggregates them into graphs.
  labels:
    deploy: prometheus
  name: prometheus
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: sourcegraph/prometheus:dev-foo
        command:
          - "yes"
        imagePullPolicy: Never
        env:
        - name: USE_KUBERNETES_DISCOVERY
          value: "true"
        terminationMessagePolicy: FallbackToLogsOnError
        name: prometheus
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        #- mountPath: /prometheus
        #  name: data
        #- mountPath: /prometheus/sg_config/add_ons
        #  name: config
      serviceAccountName: prometheus
      volumes:
      #- name: data
      #  persistentVolumeClaim:
      #    claimName: prometheus
      #- configMap:
      #    defaultMode: 464
      #    name: prometheus
      #  name: config
