apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Stores clones of repositories to perform Git operations.
  labels:
    deploy: sourcegraph
  name: gitserver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitserver
  serviceName: gitserver
  template:
    metadata:
      labels:
        app: gitserver
        group: backend
        type: gitserver
    spec:
      containers:
      - args:
        - run
        env: null
        image: index.docker.io/sourcegraph/gitserver:3.6.0-rc.2@sha256:a4d64e250de975aa8fa63d2de63920b21ec9d324c9e8552e5c1d0ccca20baac9
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: rpc
          timeoutSeconds: 5
        name: gitserver
        ports:
        - containerPort: 3178
          name: rpc
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /data/repos
          name: repos
      securityContext:
        runAsUser: 0
      volumes:
      - name: repos
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
