apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Handles repository metadata (not Git data) lookups and updates from
      external code hosts and other similar services.
  labels:
    deploy: sourcegraph
  name: repo-updater
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: repo-updater
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: repo-updater
    spec:
      containers:
      - env: null
        image: index.docker.io/sourcegraph/repo-updater:3.6.0-rc.2@sha256:fd7c7d404e75dce02a0d0f7d9402bcb3c3884686807b157493e81fa843132f25
        name: repo-updater
        ports:
        - containerPort: 3182
          name: http
        - containerPort: 6060
          name: debug
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsUser: 0
