apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for text search operations.
  labels:
    deploy: sourcegraph
  name: searcher
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: searcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: searcher
    spec:
      containers:
      - env:
        - name: SEARCHER_CACHE_SIZE_MB
          value: "100000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CACHE_DIR
          value: /mnt/cache/$(POD_NAME)
        image: index.docker.io/sourcegraph/searcher:3.6.0-rc.2@sha256:aa136a152f7e675c512dbea16fb554819832a2c651e008c62fc9c69e16ba9e97
        name: searcher
        ports:
        - containerPort: 3181
          name: http
        - containerPort: 6060
          name: debug
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 1
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /mnt/cache
          name: cache-ssd
      securityContext:
        runAsUser: 0
      volumes:
      - emptyDir: {}
        name: cache-ssd
