apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for indexed text search operations.
  labels:
    deploy: sourcegraph
  name: indexed-search
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexed-search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: indexed-search
    spec:
      containers:
      - env: null
        image: index.docker.io/sourcegraph/zoekt-webserver:19-07-16_51c44e6@sha256:4ee336b6a7141cd5e41f2233f2f71f172dfe6b5ea19b470aa5bd275b4bf4d061
        name: zoekt-webserver
        ports:
        - containerPort: 6070
          name: http
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 1
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /data
          name: disk
      - env: null
        image: index.docker.io/sourcegraph/zoekt-indexserver:19-07-16_51c44e6@sha256:18d07ece697833e03c10c7820e8c35a41882abe5a066a34afa3582518bec5525
        name: zoekt-indexserver
        ports:
        - containerPort: 6072
          name: index-http
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /data
          name: disk
      securityContext:
        runAsUser: 0
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: indexed-search
