apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Rate-limiting proxy for the GitHub API.
  labels:
    deploy: sourcegraph
  name: github-proxy
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: github-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github-proxy
    spec:
      containers:
      - env: null
        image: index.docker.io/sourcegraph/github-proxy:3.6.0-rc.2@sha256:0458eaea3fe6254de094a365d47ac7f883f74b627a198ee7ebb2d2d225baf131
        name: github-proxy
        ports:
        - containerPort: 3180
          name: http
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsUser: 0
